//AUTH
export const LOAD_USER = "LOAD_USER";
export const AUTH_FAIL = "AUTH_FAIL";
export const REGISTER_START = "REGISTER_START";
export const REGISTER_FAIL = "REGISTER_FAIL";
export const REGISTER_SUCCESS = "REGISTER_SUCCESS";

export const LOGIN_START = "LOGIN_START";
export const LOGIN_FAIL = "LOGIN_FAIL";
export const LOGIN_SUCCESS = "LOGIN_SUCCESS";

//ALERT

export const SET_ALERT = "SET_ALERT";
export const COUNT_ALERT = "COUNT_ALERT";
export const REMOVE_ALERT = "REMOVE_ALERT";
export const LOGOUT = "LOGOUT";

export const UPDATE_USER_START = "UPDATE_USER_START";
export const UPDATE_USER_FAIL = "UPDATE_USER_FAIL";
export const UPDATE_USER_SUCCESS = "UPDATE_USER_SUCCESS";

export const DELETE_USER_START = "DELETE_USER_START";
export const DELETE_USER_FAIL = "DELETE_USER_FAIL";
export const DELETE_USER_SUCCESS = "DELETE_USER_SUCCESS";

//NOTES

export const GET_NOTES_START = "GET_NOTES_START";
export const GET_NOTES_FAIL = "GET_NOTES_FAIL";
export const GET_NOTES_SUCCESS = "GET_NOTES_SUCCESS";

export const GET_ONE_NOTE_START = "GET_ONE_NOTE_START";
export const GET_ONE_NOTE_FAIL = "GET_ONE_NOTE_FAIL";
export const GET_ONE_NOTE_SUCCESS = "GET_ONE_NOTE_SUCCESS";

export const CREATE_NOTE_START = "CREATE_NOTE_START";
export const CREATE_NOTE_FAIL = "CREATE_NOTE_FAIL";
export const CREATE_NOTE_SUCCESS = "CREATE_NOTE_SUCCESS";

export const UPDATE_NOTE_START = "UPDATE_NOTE_START";
export const UPDATE_NOTE_FAIL = "UPDATE_NOTE_FAIL";
export const UPDATE_NOTE_SUCCESS = "UPDATE_NOTE_SUCCESS";

export const DELETE_NOTE_START = "DELETE_NOTE_START";
export const DELETE_NOTE_FAIL = "DELETE_NOTE_FAIL";
export const DELETE_NOTE_SUCCESS = "DELETE_NOTE_SUCCESS";
